AnimeProject/Models/Month.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnimeProject.Models
{
    public class Month
    {
        public int ID { get; set; }
        public Date Date { get; set; }
        public int Year { get; set; }

        public virtual List<Anime> Animes { get; set;  }

      
    }
}

AnimeProject/Controllers/AnimesController.cs
using AnimeProject.Data;
using AnimeProject.Interfaces;
using AnimeProject.Models;
using AnimeProject.Models.Binding;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnimeProject.Controllers

{
    [Route("[Controller]")]
    public class AnimesController : Controller
    {
        private IRepositoryWrapper repository;
        public AnimesController(IRepositoryWrapper repositoryWrapper)
        {
            repository = repositoryWrapper;
        }

        //private ApplicationDbContext dbContext;
        //public AnimesController(ApplicationDbContext applicationDbContext)
        //{
        //    dbContext = applicationDbContext;
        //}

        //Read
        public IActionResult Index()
        {
            var allanimes = repository.Animes.FindAll();
            return View(allanimes);
        }
        [Route("details/{id:int}")]
        public IActionResult Details(int id)
        {
            var animeById = repository.Animes.FindByCondition(c => c.ID == id).FirstOrDefault();
            return View(animeById);
        }

        //public IActionResult Index()
        //{
        //    var allanimes = dbContext.Animes.ToList();
        //    return View(allanimes);
        //}
        //[Route("details/{id:int}")]
        //public IActionResult Details(int id)
        //{
        //    var animeById = dbContext.Animes.FirstOrDefault(c => c.ID == id);
        //    return View(animeById);
        //}




        //Update 
        [Route("update/{id:int}")]
        public IActionResult Update(int id)
        {
            var animeById = repository.Animes.FindByCondition(c => c.ID == id).FirstOrDefault();
            return View(animeById);
        }
        [HttpPost]
        [Route("update/{id:int}")]
        public IActionResult Update(Anime anime, int id)
        {
            var animeToUpdate = repository.Animes.FindByCondition(c => c.ID == id).FirstOrDefault();
            {
               
                animeToUpdate.Name = anime.Name;
                animeToUpdate.Episodes = anime.Episodes;
                animeToUpdate.Adaptation = anime.Adaptation;
                animeToUpdate.AiringDay = anime.AiringDay;
                animeToUpdate.PictureURL = anime.PictureURL;
               
            };
            repository.Animes.Update(animeToUpdate);
            repository.Save();
            return RedirectToAction("Index");

        }
        //public IActionResult Update(int id)
        //{
        //    var animeById = dbContext.Animes.FirstOrDefault(c => c.ID == id);
        //    return View(animeById);
        //}
        //[HttpPost]
        //[Route("update/{id:int}")]
        //public IActionResult Update(Anime anime, int id)
        //{
        //    var animeToUpdate = dbContext.Animes.FirstOrDefault(c => c.ID == id);
        //    animeToUpdate.Name = anime.Name;
        //    animeToUpdate.Episodes = anime.Episodes;
        //    animeToUpdate.Adaptation = anime.Adaptation;
        //    animeToUpdate.AiringDay = anime.AiringDay;
        //    animeToUpdate.PictureURL = anime.PictureURL;
        //    dbContext.SaveChanges();
        //    return RedirectToAction("Index");

        //}

        //Delete
        [Route("delete/{id:int}")]
        public IActionResult Delete(int id)
        {
            var animeToDelete = repository.Animes.FindByCondition(c => c.ID == id).FirstOrDefault();
           repository.Animes.Delete(animeToDelete);
            repository.Save();

            return RedirectToAction("Index");

        }

        //[Route("delete/{id:int}")]
        //public IActionResult Delete(int id)
        //{
        //    var animeToDelete = dbContext.Animes.FirstOrDefault(c => c.ID == id);
        //    dbContext.Animes.Remove(animeToDelete);
        //    dbContext.SaveChanges();

        //    return RedirectToAction("Index");
        }
    }

AnimeProject/Controllers/MonthsController.cs
using AnimeProject.Data;
using AnimeProject.Interfaces;
using AnimeProject.Models;
using AnimeProject.Models.Binding;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnimeProject.Controllers
{
    [Route("[Controller]")]
    public class MonthsController : Controller
    {
        private IRepositoryWrapper repository;
        public MonthsController(IRepositoryWrapper repositoryWrapper)
        {
            repository = repositoryWrapper;
        }


        //private ApplicationDbContext dbContext;
        //public MonthsController(ApplicationDbContext applicationDbContext)
        //{
        //    dbContext = applicationDbContext;
        //}

        //Read
        [Route("")]
        public IActionResult Index()
        {
            var allMonths = repository.Months.FindAll();
            //var allMonths = dbContext.Months.ToList();
            return View(allMonths);
        }
        [Route("details/{id:int}")]
        public IActionResult Details(int id)
        {
            var monthById = repository.Months.FindByCondition(c => c.ID == id).FirstOrDefault();
            //var monthById = dbContext.Months.FirstOrDefault(c => c.ID == id);
            return View(monthById);
        }

        //Create
        [Route("create")]

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost("create")]
        public IActionResult Create(AddMonthBindingModel bindingModel)
        {
            var monthToCreate = new Month
            {
                Date = bindingModel.Date,
                Year = bindingModel.Year,

            };
            repository.Months.Create(monthToCreate);
            repository.Save();
            //dbContext.Months.Add(monthToCreate);
            //dbContext.SaveChanges();
            return RedirectToAction("Index");

        }

        //Anime section
        //Create 
        //Create
        [Route("addanime/{monthID:int}")]

        public IActionResult CreateAnime(int monthID)
        {
            var month = repository.Months.FindByCondition(c => c.ID == monthID);
            //var month = dbContext.Months.FirstOrDefault(c => c.ID == monthID);
            ViewBag.MonthDate = month.ToList()[0].Date;
            ViewBag.MonthID = month.ToList()[0].ID;
            return View();
        }
        [HttpPost]
        [Route("addanime/{monthID:int}")]
        public IActionResult CreateAnime(AddAnimeBindingModel bindingModel, int monthID)
        {
            var animeToCreate = new Anime
            {
                Name = bindingModel.Name,
                Episodes = bindingModel.Episodes,
                Adaptation = bindingModel.Adaptation,
                MonthID = monthID,
                //Month = dbContext.Months.FirstOrDefault(c => c.ID == bindingModel.MonthID),
                AiringDay = bindingModel.AiringDay,
                PictureURL = "https://i.pinimg.com/474x/84/aa/0d/84aa0dadd6cbd869bf40397a1a59e4cb.jpg"

            };
            repository.Animes.Create(animeToCreate);
            repository.Save();
            //dbContext.Animes.Add(animeToCreate);
            //dbContext.SaveChanges();
            return RedirectToAction("Index");

        }
        [Route("{id:int}/animes")]
        public IActionResult ViewAnimes(int id)
        {
            var month = repository.Months.FindByCondition(c => c.ID == id).FirstOrDefault();
            var animes = repository.Animes.FindByCondition(c => c.MonthID == id);
            //var month = dbContext.Months.FirstOrDefault(c => c.ID == id);
            //var animes = dbContext.Animes.Where(c => c.Month.ID == id).ToList();
            ViewBag.MonthDate = month.Date;
            return View(animes);
        }



        //Update 
        [Route("update/{id:int}")]
        public IActionResult Update(int id)
        {
            var monthById = repository.Months.FindByCondition(c => c.ID == id).FirstOrDefault();
            //var monthById = dbContext.Months.FirstOrDefault(c => c.ID == id);
            return View(monthById);
        }
        [HttpPost]
        [Route("update/{id:int}")]
        public IActionResult Update(Month month, int id)
        {
            repository.Months.Update(month);
            repository.Save();
            //dbContext.SaveChanges();
            return RedirectToAction("Index");

        }


        //Delete
        [Route("delete/{id:int}")]
        public IActionResult Delete(int id)
        {
            var monthToDelete = repository.Months.FindByCondition(c => c.ID == id).FirstOrDefault();
            repository.Months.Delete(monthToDelete);
           repository.Save();
            //var monthToDelete = dbContext.Months.FirstOrDefault(c => c.ID == id);
            //dbContext.Months.Remove(monthToDelete);
            //dbContext.SaveChanges();

            return RedirectToAction("Index");

        }

    }

}

AnimeProject/Views/Months/Create.cshtml
@model AnimeProject.Models.Binding.AddMonthBindingModel

@{
    ViewData["Title"] = "Index";
}

<h1>Create</h1>

<p>
    <a asp-action="Create">Create New</a>

</p>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <select asp-for="Date" class="form-control">
                    <option value="1">Janurary</option>
                    <option value="2">Feburary</option>
                    <option value="3">March</option>
                    <option value="4">April</option>
                    <option value="5">May</option>
                    <option value="6">June</option>
                    <option value="7">July</option>
                    <option value="8">August</option>
                    <option value="9">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <
            <div class="form-group">
                <input type="Submit" value="Save" class="btn btn-primary" />

            </div>

        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnimeProject/Views/Months/CreateAnime.cshtml
@model AnimeProject.Models.Binding.AddAnimeBindingModel

@{
    ViewData["Title"] = "Create Anime";

}

<h1>Create New Anime for @ViewBag.MonthDate</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAnime">
            <div asp-validation-summary="ModelOnly" class="tex-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="tex-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Episodes" class="control-label"></label>
                <input asp-for="Episodes" class="form-control" />
                <span asp-validation-for="Episodes" class="tex-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AiringDay" class="control-label"></label>
                <select asp-for="AiringDay" class="form-control">
                    <option value="1">Monday</option>
                    <option value="2">Tuesday</option>
                    <option value="3">Wednesday</option>
                    <option value="4">Thursday</option>
                    <option value="5">Friday</option>
                    <option value="6">Saturday</option>
                    <option value="7">Sunday</option>
                </select>
                <span asp-validation-for="AiringDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adaptation" class="control-label"></label>
                <select asp-for="Adaptation" class="form-control">
                    <option value="1">Yes</option>
                    <option value="2">No</option>
                </select>
                <span asp-validation-for="Adaptation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="Submit" value="Save" class="btn btn-primary" />

            </div>

        </form>
    </div>
</div>
<div>
    <a asp-action="Index" asp-controller="Animes">Back to All Animes</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnimeProject/Views/Months/Details.cshtml
@model AnimeProject.Models.Month

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cat</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Update", new { id = Model.ID }) |
    <a asp-action="Index">Back to List</a>
</div>

AnimeProject/Views/Months/Index.cshtml
@model IEnumerable<AnimeProject.Models.Month>

    @{
        ViewData["Title"] = "Index";
    }

    <h1>Index</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Year)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Update", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }) |
                        @Html.ActionLink("View Animes", "ViewAnimes", new { id = item.ID }) |
                        @Html.ActionLink("Add Anime", "CreateAnime", new { monthID = item.ID })

                    </td>
                </tr>
            }
        </tbody>
    </table>

AnimeProject/Views/Months/Update.cshtml
@model AnimeProject.Models.Month
@{
    ViewData["Title"] = "Update";
}

<h1>Update details for @Model.Date</h1>


@{
    ViewData["Title"] = "Update";
}

<h1>Update Details for @Model.Date</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <select asp-for="Date" class="form-control">
                    <option value="1">Janurary</option>
                    <option value="2">Feburary</option>
                    <option value="3">March</option>
                    <option value="4">April</option>
                    <option value="5">May</option>
                    <option value="6">June</option>
                    <option value="7">July</option>
                    <option value="8">August</option>
                    <option value="9">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="Submit" value="Save" class="btn btn-primary" />

            </div>

        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnimeProject/Views/Months/ViewAnimes.cshtml
@model IEnumerable<AnimeProject.Models.Anime>

    @{
        ViewData["Title"] = "Animes";
    }

    <h1>@ViewBag.MonthDate's Animes</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Episodes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AiringDay)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Episodes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AiringDay)
                </td>
              
            </tr>
            }
        </tbody>
    </table>